# Generated by Django 2.2 on 2019-04-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('phone_no', models.CharField(default='', max_length=16)),
                ('dob', models.DateField(default='')),
                ('sex', models.CharField(default='', max_length=6)),
                ('profession', models.CharField(default='', max_length=32)),
                ('address', models.TextField(default='', null=True)),
            ],
        ),
    ]
