# Generated by Django 2.2 on 2019-04-16 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDjango_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
