# Generated by Django 2.2 on 2019-04-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDjango_app', '0002_person_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.FileField(null=True, upload_to='../images'),
        ),
    ]
