# Generated by Django 2.2 on 2019-04-17 09:33

from django.db import migrations, models
import testDjango_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('testDjango_app', '0005_auto_20190417_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(null=True, upload_to=testDjango_app.models.update_filename),
        ),
    ]
