# Generated by Django 2.2 on 2019-04-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testDjango_app', '0007_auto_20190417_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_name',
            field=models.CharField(default='', max_length=32),
        ),
    ]
