# Generated by Django 2.2 on 2019-04-17 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testDjango_app', '0008_department_department_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departments'},
        ),
    ]
