# Generated by Django 2.2 on 2019-04-20 11:24

from django.db import migrations, models
import testDjango_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('testDjango_app', '0009_auto_20190417_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='image2',
            field=models.ImageField(null=True, upload_to=testDjango_app.models.update_filename1),
        ),
    ]
