# Generated by Django 2.2 on 2019-04-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testDjango_app', '0010_person_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='address',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.RemoveField(
            model_name='person',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='person',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='person',
            name='sex',
        ),
    ]
